"""Week 19 temporal regime audit — driver.

Question (Ioan): which simulations contain Keyhole and Conduction, especially Keyhole followed by only Conduction
and alternating regimes, and can the monitor time series explain these transitions and the loss of OLD's
max-depth/label relationship on October NEW?

Evidence classes kept apart in every output: OBSERVATION (frame labels, monitor rows), PHYSICAL INTERPRETATION
(hypotheses; bounding boxes alone never establish cavity morphology or causation), PREDICTIVE (existing
out-of-fold predictions only; no model is fitted here).  New targets motivated by the NEW labels are POST-HOC.

Steps:  python -m src.week19_temporal_audit labels | series | tables | oof | figures | all
Outputs: outputs/week19_temporal_regime_audit/
"""
from __future__ import annotations

import json
import math
import sys

import numpy as np
import pandas as pd

from src.week19_sources import NEW_REV, OLD_REV, OUT, POPULATION, eligible_new, eligible_old
from src.week19_sequences import load_labels, sequence_table

TAB = OUT / "tables"
FIG = OUT / "figures"
CACHE = OUT / "_cache"            # git-ignored intermediate (frame maps); regenerated by `series`
W18 = OUT.parent / "week18_independent_research"
REV = {"OLD": OLD_REV, "NEW": NEW_REV}
DESCRIPTOR_ORDER = ["conduction_only", "K_then_C__no_later_K", "alternating__terminal_C", "C_then_K__K_at_end",
                    "alternating__K_at_end", "keyhole_only__K_at_end", "forming_only", "no_physical_label"]


def _w(df, name, **kw):
    TAB.mkdir(parents=True, exist_ok=True)
    df.to_csv(TAB / name, index=False, lineterminator="\n", **kw)


# ------------------------------------------------------------------ OLD reference threshold (recovered, not tuned)
def u_reference():
    """Recover the OLD max-depth reference threshold from the existing rules (OLD data only)."""
    from sklearn.linear_model import LogisticRegression
    pop = pd.read_csv(POPULATION, usecols=["experiment_name", "has_keyhole", "max_depth_um"])
    y = pop.has_keyhole.map({True: 1, False: 0, "True": 1, "False": 0}).astype(int).to_numpy()
    d = pop.max_depth_um.to_numpy(float); t = np.log(d)
    kh, nk = t[y == 1], t[y == 0]
    rec = {"source": "outputs/week7_06_real_data_boundary_active_level_set/primary_common_population.csv (max_depth_um, has_keyhole)",
           "n_old": int(len(y)), "n_keyhole": int(y.sum()),
           "min_keyhole_max_depth_um": float(np.exp(kh.min())), "max_nonkeyhole_max_depth_um": float(np.exp(nk.max())),
           "separable": bool(nk.max() < kh.min())}
    if rec["separable"]:
        u = float(np.exp(.5 * (nk.max() + kh.min()))); rule = "midpoint of the separated log-depth gap"
    else:
        lr = LogisticRegression(C=1e6, max_iter=5000).fit(t[:, None], y)
        u = float(np.exp(-lr.intercept_[0] / lr.coef_[0, 0])); rule = "1-D logistic regression on log depth (C=1e6), the non-separable branch"
    rec.update({"u_ref_um": u, "rule": f"E1 learned-threshold procedure (src/week18_engine.py::DepthGPR.fit) applied to all 405 OLD runs: {rule}",
                "engine_default_um": 111.0, "week18_count_rule_um": 111.2})
    # descriptive single-threshold BA on OLD (oracle on OLD itself; context only)
    cand = np.unique(d)
    best = max(((0.5 * ((d[y == 1] >= c).mean() + (d[y == 0] < c).mean()), c) for c in cand))
    rec["old_best_single_threshold_BA"] = float(best[0]); rec["old_best_single_threshold_um"] = float(best[1])
    for name, c in [("u_ref", u), ("111.0", 111.0), ("111.2", 111.2)]:
        rec[f"old_BA_at_{name}"] = float(0.5 * ((d[y == 1] >= c).mean() + (d[y == 0] < c).mean()))
    return rec


# ------------------------------------------------------------------ Phase 1: labels and sequences
def step_labels():
    frames, audit = load_labels()
    seq, epis = sequence_table(frames)
    old, new = eligible_old(), eligible_new()
    frozen = pd.concat([old[["sim_id", "has_keyhole"]].assign(frozen_source="primary_common_population.csv"),
                        new[["sim_id", "has_keyhole"]].assign(frozen_source="week12 audit/new136.csv (Week 11 sealed oracle)")])
    seq = seq.merge(frozen.rename(columns={"has_keyhole": "has_keyhole_frozen"}), on="sim_id", how="left")
    seq["has_keyhole_discrepancy"] = (seq.has_keyhole_frozen != seq.has_keyhole_reproduced).astype(int)
    inputs = pd.concat([old[["sim_id", "P", "VX", "LS", "ST"]], new[["sim_id", "P", "VX", "LS", "ST"]]])
    seq = seq.merge(inputs, on="sim_id", how="left")
    # Week 7 cross-check on OLD (same ordering rule; label_final strings)
    w7 = pd.read_csv(OUT.parent / "week7_01_sph_v2_audit/experiment_label_sequences.csv")
    chk = seq[seq.campaign == "OLD"].merge(w7, left_on="sim_id", right_on="experiment_name", suffixes=("", "_w7"))
    import hashlib
    inv = {"IE": "Initial Emptiness", "F": "Forming Phase", "C": "Conduction", "K": "Keyhole", "SS": "Scanning Stopped",
           "SoS": "Solidifying Stopped", "SB": "Screenshot Bug", "U": "Unsure"}
    h = frames[frames.campaign == "OLD"].groupby("sim_id").code.apply(lambda c: hashlib.sha256("\n".join(inv[x] for x in c).encode()).hexdigest())
    chk["w7_hash_match"] = chk.sim_id.map(h) == chk.label_sequence_sha256_w7
    w7c = {"rows_compared": int(len(chk)),
           "has_keyhole_equal": int((chk.has_keyhole_reproduced == chk.has_keyhole.astype(int)).sum()),
           "keyhole_frame_count_equal": int((chk.n_K == chk.keyhole_frame_count).sum()),
           "keyhole_segment_count_equal": int((chk.n_K_runs == chk.keyhole_segment_count).sum()),
           "fraction_equal": int(np.isclose(chk.frac_K_FCK.fillna(-1), chk.keyhole_fraction_of_relevant_physical_frames.fillna(-1)).sum()),
           "label_sequence_sha256_equal": int(chk.w7_hash_match.sum()),
           "w7_transient_by_sequence_true": int(chk.keyhole_transient_by_sequence.sum()),
           "w7_persistent_to_last_physical_true": int(chk.keyhole_persistent_to_last_physical_frame.sum()),
           "w7_transient_but_final_active_K": int((chk.keyhole_transient_by_sequence & (chk.final_active_regime == "K")).sum())}
    audit["week7_cross_check"] = w7c
    # 49 Bug-withheld NEW runs: membership only (their labels are not interpreted)
    bug = pd.read_csv(OUT.parent / "week11_bug_audit/simulation_bug_status.csv")
    audit["week11_bug_status_columns"] = bug.columns.tolist()
    CACHE.mkdir(parents=True, exist_ok=True)
    frames.to_pickle(CACHE / "frames.pkl")
    seq.to_pickle(CACHE / "sequences.pkl"); epis.to_pickle(CACHE / "episodes.pkl")
    (OUT / "provenance").mkdir(parents=True, exist_ok=True)
    (OUT / "provenance" / "label_membership_audit.json").write_text(json.dumps(audit, indent=1, default=str))
    print(json.dumps({k: v for k, v in audit.items() if k != "old_not_eligible"}, indent=1, default=str))
    print(seq.groupby("campaign").descriptor.value_counts().to_string())
    return frames, seq, epis, audit


# ------------------------------------------------------------------ Phase 1/3: monitor series per simulation
def step_series(workers=6):
    from src.week19_series import _check_constants, run_all
    if not _check_constants():
        raise RuntimeError("Week 6/7 window constants changed")
    u = u_reference()
    (OUT / "provenance").mkdir(parents=True, exist_ok=True)
    (OUT / "provenance" / "old_reference_threshold.json").write_text(json.dumps(u, indent=1))
    frames = pd.read_pickle(CACHE / "frames.pkl")
    ser, fmap = run_all(frames, REV, u["u_ref_um"], workers=workers)
    ser.to_pickle(CACHE / "series.pkl"); fmap.to_pickle(CACHE / "frame_map.pkl")
    print(ser.failure.fillna("").replace("", "ok").value_counts().head(10).to_string())
    return ser, fmap, u


# ------------------------------------------------------------------ tables: registry, episodes, switches
def _rel_paths(sid, camp):
    return {"evidence_revision": REV[camp], "evidence_ledger": "labels_new_data_4_prep.csv" if camp == "NEW" else "labels_partition_<n>_<partition>.csv",
            "evidence_frames_csv": f"{sid}/frames.csv", "evidence_iter": f"{sid}/monitor/iter.dat",
            "evidence_time": f"{sid}/monitor/time.dat", "evidence_bounds": f"{sid}/monitor/position-bounds_melt.dat"}


def frame_intervals(tf):
    """Midpoint (frame-centred) intervals for sorted frame times; the first/last frame interval is clipped at its own time."""
    tf = np.asarray(tf, float)
    if len(tf) < 2:
        return np.zeros(len(tf))
    mid = 0.5 * (tf[1:] + tf[:-1])
    return np.r_[mid, tf[-1]] - np.r_[tf[0], mid]


def _switch_location(t_from, t_to, row):
    cut, ex, last_f = row["active_cutoff_ms"], row["derived_exit_ms"], row["last_F_ms"]
    if not (np.isfinite(t_from) and np.isfinite(t_to)):
        return "timing_unavailable"
    if np.isfinite(last_f) and t_to <= last_f:
        return "overlaps_forming_labels"          # Forming Phase frames still occur at or after the new regime frame
    if np.isfinite(cut) and t_to <= cut:
        return "established_active_window"
    if np.isfinite(cut) and t_from >= cut:
        return "late_after_derived_exit" if (np.isfinite(ex) and t_from >= ex) else "late_after_active_cutoff"
    return "straddles_active_cutoff" if np.isfinite(cut) else "window_unavailable"


def timed_tables(frames, fmap, ser, epis):
    """K runs and active-regime switches with monitor times; time-weighted K fractions (midpoint rule)."""
    fm = fmap.merge(frames[["sim_id", "frame_pos", "campaign"]], on=["sim_id", "frame_pos"], how="left")
    S = ser.set_index("sim_id")
    tmap = {sid: g.sort_values("frame_pos") for sid, g in fm.groupby("sim_id")}
    ep = epis.copy()
    starts, ends, lo, hi = [], [], [], []
    for r in ep.itertuples(index=False):
        tf = tmap[r.sim_id].time_ms.to_numpy(); n = len(tf)
        starts.append(tf[r.start_pos]); ends.append(tf[r.end_pos])
        lo.append(tf[r.start_pos - 1] if r.start_pos > 0 else np.nan); hi.append(tf[r.end_pos + 1] if r.end_pos + 1 < n else np.nan)
    ep["start_ms"], ep["end_ms"], ep["bracket_lo_ms"], ep["bracket_hi_ms"] = starts, ends, lo, hi
    ep["observed_duration_ms"] = ep.end_ms - ep.start_ms                  # first-to-last labelled K frame, no extrapolation
    ep["bracketed_max_duration_ms"] = ep.bracket_hi_ms - ep.bracket_lo_ms  # upper bound between the neighbouring non-K frames
    ep = ep.merge(S[["derived_exit_ms", "active_cutoff_ms", "first_SS_ms", "last_F_ms"]], left_on="sim_id", right_index=True, how="left")
    ep["start_over_exit"] = ep.start_ms / ep.derived_exit_ms; ep["end_over_exit"] = ep.end_ms / ep.derived_exit_ms
    trans, extra = [], []
    for sid, g in tmap.items():
        codes = g.code.to_numpy(); tf = g.time_ms.to_numpy(); pos = g.frame_pos.to_numpy()
        act = np.flatnonzero(np.isin(codes, ["C", "K"]))
        row = S.loc[sid] if sid in S.index else pd.Series({"active_cutoff_ms": np.nan, "derived_exit_ms": np.nan, "last_F_ms": np.nan, "first_SS_ms": np.nan})
        for a, b in zip(act[:-1], act[1:]):
            if codes[a] == codes[b]:
                continue
            mid = codes[a + 1:b]
            ex = row["derived_exit_ms"]; ss = row["first_SS_ms"]
            trans.append({"sim_id": sid, "campaign": g.campaign.iloc[0], "type": f"{codes[a]}_to_{codes[b]}",
                          "from_pos": int(pos[a]), "to_pos": int(pos[b]), "from_ms": tf[a], "to_ms": tf[b],
                          "bracket_width_ms": tf[b] - tf[a], "intermediate_labels": "+".join(sorted(set(mid))) if len(mid) else "none",
                          "location": _switch_location(tf[a], tf[b], row), "from_over_exit": tf[a] / ex if np.isfinite(ex) else np.nan,
                          "after_first_scanning_stopped": int(bool(np.isfinite(ss) and tf[a] >= ss))})
        ok = np.isfinite(tf)
        w = np.zeros(len(tf)); w[ok] = frame_intervals(tf[ok])
        kc = np.isin(codes, ["C", "K"]); fck = np.isin(codes, ["F", "C", "K"])
        extra.append({"sim_id": sid,
                      "K_time_frac_FCK_midpoint": w[codes == "K"].sum() / w[fck].sum() if w[fck].sum() > 0 else np.nan,
                      "K_time_frac_KC_midpoint": w[codes == "K"].sum() / w[kc].sum() if w[kc].sum() > 0 else np.nan,
                      "FCK_time_covered_ms": w[fck].sum(),
                      "active_span_first_to_last_CK_ms": (tf[act[-1]] - tf[act[0]]) if (len(act) and ok[act].all()) else np.nan,
                      "frames_with_time": int(ok.sum())})
    return ep, pd.DataFrame(trans), pd.DataFrame(extra)


def record_flags(r):
    f = []
    if r.get("bounds_time_rows_match", 1) == 0:
        f.append("bounds_time_row_mismatch")
    if r.get("recording_ends_before_90pct_domain", 0) == 1:
        f.append("recording_ends_before_90pct_domain")
    if r.get("timing_mapping_ok", 1) != 1:
        f.append("frame_timing_unmappable")
    if r["descriptor"] in ("forming_only", "no_physical_label"):
        f.append("no_active_regime_label")
    if r.get("F_after_active_onset", 0) == 1:
        f.append("F_after_active_onset")
    if r.get("IE_after_physical_onset", 0) == 1:
        f.append("IE_after_physical_onset")
    if r.get("max_depth_whole_is_last_row", 0) == 1:
        f.append("max_depth_in_last_row")
    if min(r.get("frames_csv_rows_match_ledger", 1), r.get("frames_csv_timesteps_match_ledger", 1), r.get("frames_csv_labels_match_label_final", 1)) == 0:
        f.append("frames_csv_ledger_disagreement")
    return ";".join(f)


def step_tables():
    from src.week19_series import parse_name
    frames = pd.read_pickle(CACHE / "frames.pkl"); seq = pd.read_pickle(CACHE / "sequences.pkl"); epis = pd.read_pickle(CACHE / "episodes.pkl")
    ser = pd.read_pickle(CACHE / "series.pkl"); fmap = pd.read_pickle(CACHE / "frame_map.pkl")
    ep, trans, extra = timed_tables(frames, fmap, ser, epis)
    reg = seq.merge(ser.drop(columns=["campaign"]), on="sim_id", how="left").merge(extra, on="sim_id", how="left")
    lr = ep.groupby("sim_id").agg(longest_K_run_observed_ms=("observed_duration_ms", "max"),
                                  longest_K_run_bracketed_max_ms=("bracketed_max_duration_ms", "max"),
                                  K_run_touches_last_frame=("right_censored_by_last_frame", "max"))
    reg = reg.merge(lr, on="sim_id", how="left")
    meta = pd.DataFrame([parse_name(s) for s in reg.sim_id]).rename(columns={"experiment_name": "sim_id"})
    reg = reg.merge(meta[["sim_id", "XI", "XF", "XL", "TE", "DT", "folder_hash"]], on="sim_id", how="left")
    reg["LS_um_radius"] = reg.LS * 1e6
    reg["scan_end_label_observed"] = ((reg.n_SS + reg.n_SoS) > 0).astype(int)
    reg["K_at_end_without_scan_end_label"] = ((reg.K_ongoing_at_observation_end == 1) & (reg.scan_end_label_observed == 0)).astype(int)
    for c in ("alt_K_FCK_ge05", "alt_K_FCK_ge10", "alt_K_KC_ge05", "alt_K_KC_ge10"):
        reg[f"class_change_{c}"] = ((reg.has_keyhole_frozen == 1) & (reg[c] == 0)).astype(int)
    reg = reg.merge(pd.DataFrame([{"sim_id": s, **_rel_paths(s, c)} for s, c in zip(reg.sim_id, reg.campaign)]), on="sim_id", how="left")
    bug = pd.read_csv(OUT.parent / "week11_bug_audit/simulation_bug_status.csv").rename(columns={"simulation_id": "sim_id"})
    reg = reg.merge(bug[["sim_id", "technical_usability_status"]], on="sim_id", how="left")
    reg["eligibility"] = np.where(reg.campaign == "OLD", "primary_common_population_405", "week11_included_manifest_136")
    reg["record_flags"] = [record_flags(r) for r in reg.to_dict("records")]
    first = ["sim_id", "campaign", "partition", "folder_hash", "P", "VX", "LS", "LS_um_radius", "ST", "XI", "XF", "XL", "TE", "DT",
             "eligibility", "technical_usability_status", "bug_free_values", "correctly_finished_values", "has_keyhole_frozen",
             "has_keyhole_reproduced", "has_keyhole_discrepancy", "descriptor", "record_flags"]
    reg = reg[first + [c for c in reg.columns if c not in first]]
    _w(reg, "temporal_registry.csv")
    _w(ep, "k_runs.csv"); _w(trans, "regime_switches.csv")
    fl = fmap.merge(frames[["sim_id", "frame_pos", "campaign", "label_final", "label_1", "label_2", "source_row"]], on=["sim_id", "frame_pos"])
    fl.to_csv(TAB / "frame_level_map.csv.gz", index=False, compression="gzip", lineterminator="\n")
    reg.to_pickle(CACHE / "registry.pkl"); trans.to_pickle(CACHE / "switches.pkl"); ep.to_pickle(CACHE / "k_runs.pkl")
    print(reg.groupby("campaign").descriptor.value_counts().to_string())
    return reg, ep, trans


# ------------------------------------------------------------------ Phases 2-3 and OOF
def step_analysis():
    from src.week19_analysis import depth_tables, negative_cases, nearest_neighbours, oof, phase2_tables
    u = json.loads((OUT / "provenance" / "old_reference_threshold.json").read_text())
    reg = pd.read_pickle(CACHE / "registry.pkl"); trans = pd.read_pickle(CACHE / "switches.pkl")
    d, sep = depth_tables(reg, u)
    cases, mech = negative_cases(d, reg, u)
    reg2, box = phase2_tables(reg, trans)
    nn = nearest_neighbours(reg, d, cases.sim_id.tolist())
    diag, per, uu = oof(reg)
    d.to_pickle(CACHE / "depth.pkl"); cases.to_pickle(CACHE / "cases.pkl")
    print(mech.to_string()); print(sep[(sep.variant == "full")][["definition", "population", "AUC", "uref_BA", "oldE1thr_BA", "oracle_BA_same_population"]].to_string())
    return d, sep, cases


def representative_selection(reg, cases):
    """Deterministic: per (campaign, descriptor) the run whose K/(F+C+K) is closest to the group median (VX median for
    conduction-only), among runs with exact timing and aligned bounds; plus the verified matched NEW pair."""
    ok = reg[(reg.timing_mapping_ok == 1) & (reg.bounds_time_rows_match == 1)]
    pick = []
    for camp, desc, role in [("OLD", "K_then_C__no_later_K", "K then C, no later K"), ("NEW", "K_then_C__no_later_K", "K then C, no later K"),
                             ("OLD", "alternating__terminal_C", "alternating (C between K blocks)"), ("NEW", "alternating__terminal_C", "alternating (C between K blocks)"),
                             ("OLD", "keyhole_only__K_at_end", "K ongoing at observation end"), ("NEW", "C_then_K__K_at_end", "K ongoing at observation end"),
                             ("OLD", "conduction_only", "Conduction only")]:
        g = ok[(ok.campaign == camp) & (ok.descriptor == desc)]
        if not len(g):
            g = ok[(ok.campaign == camp) & ok.descriptor.str.startswith(desc.split("__")[0])]
        if not len(g):
            continue
        key = "VX" if desc == "conduction_only" else "frac_K_FCK"
        j = (g[key] - g[key].median()).abs().sort_values(kind="stable").index[0]
        pick.append({"sim_id": g.loc[j, "sim_id"], "role": role, "rule": f"closest to the {camp} {desc} median of {key} (n={len(g)})"})
    for h, role in [("P-387p361336282_VX-0p960187357846_LS-4p72484046084e-05_ST-390p52586458_M-TI64_XI-0p0002_XF-0p0014_XL-0p0012_TE-0p0021_DT-5p02414509376e-06_H-b302fc6cbd", "matched pair: NEW has_keyhole=0"),
                    ("P-380p041479483_VX-0p952843483906_LS-4p56527036263e-05_ST-376p177191048_M-TI64_XI-0p0002_XF-0p0014_XL-0p0012_TE-0p0021_DT-5p0628678104e-06_H-b7e3ed2e12", "matched pair: NEW has_keyhole=1")]:
        pick.append({"sim_id": h, "role": role, "rule": "brief-named pair, verified by full name (the H suffix b302fc6cbd is shared by two NEW runs)"})
    sel = pd.DataFrame(pick).drop_duplicates("sim_id")
    _w(sel.merge(reg[["sim_id", "campaign", "descriptor", "collapsed_sequence", "P", "VX", "LS_um_radius", "ST", "frac_K_FCK", "frac_K_KC"]], on="sim_id"),
       "representative_cases.csv")
    return sel


def step_ke():
    """Focused kinetic-energy download: representative cases and the 12 NEW negatives only."""
    from src.week19_sources import KE_FILE, run_download
    reg = pd.read_pickle(CACHE / "registry.pkl"); cases = pd.read_pickle(CACHE / "cases.pkl")
    sel = representative_selection(reg, cases)
    ids = list(dict.fromkeys(sel.sim_id.tolist() + cases.sim_id.tolist()))
    paths = [f"{s}/{KE_FILE}" for s in ids]
    run_download(include=paths)
    return sel


def _series_cache(ids, reg):
    from src.week19_series import series_for
    frames = pd.read_pickle(CACHE / "frames.pkl")
    u = json.loads((OUT / "provenance" / "old_reference_threshold.json").read_text())["u_ref_um"]
    R = reg.set_index("sim_id")
    return {s: series_for(s, R.loc[s, "campaign"], frames, u)[2] for s in ids}


def _ke(ids, reg):
    from src.week19_sources import KE_FILE, local_file
    out = {}
    R = reg.set_index("sim_id")
    for s in ids:
        rev = REV[R.loc[s, "campaign"]]
        try:
            ke = np.loadtxt(local_file(rev, f"{s}/{KE_FILE}"), ndmin=1) * 1e9
            t = np.loadtxt(local_file(rev, f"{s}/monitor/time.dat"), ndmin=1) * 1e3
            n = min(len(ke), len(t))          # plotting only; row-count differences are reported, never repaired
            out[s] = (t[:n], ke[:n], len(ke), len(t))
        except FileNotFoundError:
            pass
    return out


def step_figures():
    from src import week19_figures as F
    u = json.loads((OUT / "provenance" / "old_reference_threshold.json").read_text())
    reg = pd.read_pickle(CACHE / "registry.pkl"); trans = pd.read_pickle(CACHE / "switches.pkl")
    d = pd.read_pickle(CACHE / "depth.pkl"); cases = pd.read_pickle(CACHE / "cases.pkl")
    fmap = pd.read_pickle(CACHE / "frame_map.pkl")
    sel = pd.read_csv(TAB / "representative_cases.csv")
    paths = [F.descriptors_by_group(reg), F.kfraction_vs_vx(reg), F.switch_timing(trans), F.depth_definitions(d, u)]
    ser = _series_cache(list(dict.fromkeys(cases.sim_id.tolist() + sel.sim_id.tolist())), reg)
    paths.append(F.new_negatives(cases, ser, fmap, reg, u))
    ke = _ke(sel.sim_id.tolist() + cases.sim_id.tolist(), reg)
    _w(pd.DataFrame([{"sim_id": s, "ke_rows": v[2], "time_rows": v[3], "rows_match": int(v[2] == v[3])} for s, v in ke.items()]), "kinetic_energy_row_check.csv")
    paths += F.representative(sel, ser, {s: (v[0], v[1]) for s, v in ke.items()}, fmap, reg, u)
    _w(pd.DataFrame({"figure": paths}), "figure_manifest.csv")
    return paths


# ------------------------------------------------------------------ reproduction and provenance checks
def step_checks():
    from src.week19_sources import NEW_LABEL_SHA256, POPULATION_SHA256, PROV, sha256_file
    checks = []

    def add(cid, desc, ok, detail):
        checks.append({"check": cid, "description": desc, "status": ok if isinstance(ok, str) else ("PASS" if ok else "FAIL"), "detail": detail})
    reg = pd.read_pickle(CACHE / "registry.pkl"); d = pd.read_pickle(CACHE / "depth.pkl")
    audit = json.loads((PROV / "label_membership_audit.json").read_text())
    man = pd.read_csv(PROV / "download_manifest.csv")
    add("C01", "frozen OLD population bytes", sha256_file(POPULATION) == POPULATION_SHA256, f"sha256 {POPULATION_SHA256[:12]}...")
    nl = man[man.path == "labels_new_data_4_prep.csv"]
    from src.week19_sources import local_file
    add("C02", "NEW annotation source bytes (12,397,054 B, audited SHA-256)", sha256_file(local_file(NEW_REV, "labels_new_data_4_prep.csv")) == NEW_LABEL_SHA256 and bool(nl.verified.all()),
        f"sha256 {NEW_LABEL_SHA256[:12]}...; LFS sha256 equals the pinned tree")
    vc = man.groupby(["revision", "source"]).verified.agg(["size", "sum"]).reset_index()
    add("C03", "every used raw file verified against the pinned tree (size + Git blob SHA-1 or LFS SHA-256)", bool(man.verified.all()),
        "; ".join(f"{r.revision[:8]} {r.source}: {int(r['sum'])}/{int(r['size'])}" for _, r in vc.iterrows()))
    add("C04", "OLD ledgers: 407 experiments, 405 eligible present, the 2 documented exclusions", audit["old_ledger_experiments"] == 407 and audit["old_eligible_present"] == 405
        and sorted(s.split("_H-")[-1] for s in audit["old_not_eligible"]) == ["4ecd858c02", "f4a4199ba7"], f"not eligible: {[s.split('_H-')[-1] for s in audit['old_not_eligible']]}")
    bug = pd.read_csv(OUT.parent / "week11_bug_audit/simulation_bug_status.csv")
    from src.week19_sources import NEW_REV as NR, local_file as lf
    names = set(pd.read_csv(lf(NR, "labels_new_data_4_prep.csv"), usecols=["name"]).name)
    withheld = set(bug.simulation_id[bug.bug_affected.astype(str) == "True"])
    add("C05", "NEW: 185 names, 136 eligible, the 49 non-eligible are exactly the Week 11 Bug-affected runs", len(names) == 185 and audit["new_eligible_present"] == 136 and (names - set(reg.sim_id)) == withheld,
        f"185 names; 136 eligible; 49 non-eligible == bug_affected: {(names - set(reg.sim_id)) == withheld}; their labels were not interpreted")
    for camp in ("OLD", "NEW"):
        s = reg[reg.campaign == camp]
        add(f"C06{camp[0]}", f"has_keyhole reproduced from label_final ({camp})", int(s.has_keyhole_discrepancy.sum()) == 0,
            f"{int((s.has_keyhole_discrepancy == 0).sum())}/{len(s)} equal; positives {int(s.has_keyhole_reproduced.sum())}; discrepancies: {';'.join(s.sim_id[s.has_keyhole_discrepancy == 1]) or 'none'}")
    w7 = audit["week7_cross_check"]
    add("C07", "Week 7 OLD sequence audit reproduced (has_keyhole, K frames, K segments, K/(F+C+K), label-sequence SHA-256)",
        all(w7[k] == w7["rows_compared"] for k in ("has_keyhole_equal", "keyhole_frame_count_equal", "keyhole_segment_count_equal", "fraction_equal", "label_sequence_sha256_equal")),
        json.dumps(w7))
    fc = reg[["frames_csv_rows_match_ledger", "frames_csv_timesteps_match_ledger", "frames_csv_labels_match_label_final", "frames_csv_frame_idx_contiguous"]]
    add("C08", "frames.csv agrees with the ledgers (rows, timesteps, labels, contiguous frame_idx)", bool((fc == 1).all().all()),
        "; ".join(f"{c}: {int((fc[c] == 1).sum())}/{len(fc)}" for c in fc.columns))
    add("C09", "every labelled frame maps to exactly one iter.dat row (exact integer match)", int(reg.frames_unmatched_to_iter.fillna(1).sum()) == 0,
        f"unmatched frames {int(reg.frames_unmatched_to_iter.fillna(0).sum())}; simulations with timing failures: {int((reg.timing_mapping_ok != 1).sum())}")
    add("C10", "timestep x nominal DT is not monitor time (information)", "INFO",
        f"median relative error {reg.nominal_dt_time_rel_error_median.median():+.3f}; max |rel| {reg.nominal_dt_time_rel_error_max_abs.max():.3f}")
    for camp in ("OLD", "NEW"):
        s = d[d.campaign == camp]
        add(f"C11{camp[0]}", f"frozen whole-record max reproduced ({camp})", float(s.max_depth_abs_diff_vs_frozen.max()) < 1e-9,
            f"max |diff| {s.max_depth_abs_diff_vs_frozen.max():.2e} um over {int(s.max_depth_abs_diff_vs_frozen.notna().sum())}")
    s = d[d.campaign == "OLD"]
    add("C12", "Week 7 G3 and T0 depth reproduced on OLD", float(s.G3_abs_diff_vs_week7.max()) < 1e-6 and float(s.T0_abs_diff_vs_week7.max()) < 1e-6,
        f"G3 max |diff| {s.G3_abs_diff_vs_week7.max():.2e} (n={int(s.G3_abs_diff_vs_week7.notna().sum())}); T0 max |diff| {s.T0_abs_diff_vs_week7.max():.2e} (n={int(s.T0_abs_diff_vs_week7.notna().sum())})")
    add("C13", "derived exit and 90 % active cutoff reproduce Week 7 (OLD)", float(s.exit_abs_diff_vs_week7_ms.max()) < 1e-9 and float(s.cutoff_abs_diff_vs_week7_ms.max()) < 1e-9,
        f"exit max |diff| {s.exit_abs_diff_vs_week7_ms.max():.2e} ms; cutoff {s.cutoff_abs_diff_vs_week7_ms.max():.2e} ms")
    D = d.set_index("sim_id"); R = reg.set_index("sim_id")
    f4 = next(i for i in D.index if i.endswith("H-f4fc937e86")); c29 = next(i for i in D.index if i.endswith("H-29cf03a279"))
    e7 = [i for i in D.index if i.endswith("H-e7dbd8e5ce") and R.loc[i, "campaign"] == "NEW" and R.loc[i, "has_keyhole_frozen"] == 0][0]
    r = D.loc[f4]
    add("C14a", "H-f4fc937e86: whole max 311.99990 um at 2.042652 ms after exit 1.270891 ms; active max 110.75500; G3 93.83694; >=300 um rows 18,065 in 3 episodes",
        abs(r.max_depth_whole_um - 311.9999) < 5e-5 and abs(r.max_depth_whole_ms - 2.042652) < 5e-6 and abs(r.derived_exit_ms - 1.270891) < 5e-6
        and abs(r.A_active_max_um - 110.755) < 5e-5 and abs(r.G3_persistent_depth_um - 93.83694) < 5e-5 and int(r.rows_ge300) == 18065 and int(r.episodes_ge300) == 3,
        f"max {r.max_depth_whole_um:.5f} at {r.max_depth_whole_ms:.6f} ms; exit {r.derived_exit_ms:.6f}; A {r.A_active_max_um:.5f}; G3 {r.G3_persistent_depth_um:.5f}; "
        f">=300 rows {int(r.rows_ge300)} in {int(r.episodes_ge300)} episodes, longest {r.longest_episode_ge300_ms:.6f} ms")
    r = D.loc[c29]
    add("C14b", "H-29cf03a279: max 131.19130 um inside the pipeline active window and adaptive interior (0.4303165 ms); G3 119.66220",
        abs(r.max_depth_whole_um - 131.1913) < 5e-5 and r.max_depth_whole_location == "active_window" and int(r.max_depth_whole_in_interior) == 1
        and abs(r.max_depth_whole_ms - 0.4303165) < 5e-7 and abs(r.G3_persistent_depth_um - 119.6622) < 5e-5,
        f"max {r.max_depth_whole_um:.5f} at {r.max_depth_whole_ms:.7f} ms ({r.max_depth_whole_location}, interior={int(r.max_depth_whole_in_interior)}, "
        f"manual-label phase: {r.max_depth_whole_label_phase}); G3 {r.G3_persistent_depth_um:.5f} (event {r.G3_event_label_phase})")
    g = R.loc[e7]
    add("C14c", "H-e7dbd8e5ce: max 144.97870 um; 40,805 bounds vs 40,803 time rows; 33 IE + 17 F, no C/K",
        abs(D.loc[e7, "max_depth_whole_um"] - 144.9787) < 5e-5 and int(g.bounds_rows) == 40805 and int(g.time_rows) == 40803 and int(g.n_IE) == 33 and int(g.n_F) == 17 and int(g.n_C + g.n_K) == 0,
        f"max {D.loc[e7, 'max_depth_whole_um']:.5f}; rows {int(g.bounds_rows)}/{int(g.time_rows)}; IE {int(g.n_IE)}, F {int(g.n_F)}, C {int(g.n_C)}, K {int(g.n_K)}; last row max: {int(g.max_depth_whole_is_last_row)}")
    caches = [p for p in W18.rglob("*") if p.is_file() and "cache" in str(p.parent) and any(f"__r{k:03d}_" in p.name for k in range(17, 21))]
    add("C15", "C3 (repeats 17-20) unused: no Week 18 cache file for repeats 17-20 (verified, not executed)", len(caches) == 0, f"{len(caches)} cache files for repeats 17-20")
    a = pd.read_csv(W18 / "phase3/depth3/aulc_real.csv")
    m = a.groupby(["task", "arm"]).BA_AULC.mean().round(4)
    want = {("R3_OLD", "GPR_depth|mlii|straddle"): 0.9443, ("R3_OLD", "G3|mlii|margin"): 0.9237, ("R3_OLD", "M3|mlii|margin"): 0.9299,
            ("R1_POOLED", "GPR_depth|mlii|straddle"): 0.9474, ("R1_POOLED", "G3|mlii|margin"): 0.9479, ("R1_POOLED", "M3|mlii|margin"): 0.9499,
            ("R3_NEW", "GPR_depth|mlii|straddle"): 0.6507, ("R3_NEW", "G3|mlii|margin"): 0.6713, ("R3_NEW", "M3|mlii|margin"): 0.6014}
    add("C16", "historical DEV BA AULC reference values (repeats 1-8; phase3/depth3/aulc_real.csv)", all(m.loc[k] == v for k, v in want.items()),
        "; ".join(f"{k[0]} {k[1].split('|')[0]} {m.loc[k]:.4f}" for k in want))
    u = json.loads((PROV / "old_reference_threshold.json").read_text())
    add("C17", "OLD reference depth threshold recovered with the existing E1 rule on OLD only", "INFO", f"u_ref {u['u_ref_um']:.4f} um; {u['rule']}; OLD BA at u_ref {u['old_BA_at_u_ref']:.4f}")
    add("C18", "population counts", (reg.campaign == "OLD").sum() == 405 and reg[reg.campaign == "OLD"].has_keyhole_frozen.sum() == 73 and (reg.campaign == "NEW").sum() == 136
        and reg[reg.campaign == "NEW"].has_keyhole_frozen.sum() == 124 and len(reg) == 541, "OLD 405 (73 positive); NEW 136 (124 positive, 12 negative); POOLED 541")
    from src.week19_series import _check_constants
    add("C19", "window constants equal the executable Week 6/7 constants", _check_constants(), "0.90 cutoff, 20 % T0, 50 rows, 50 um margins, 50 um window, 12 um wall extension")
    oo = pd.read_csv(TAB / "oof_predictions_final_budget.csv.gz")
    cov = oo.groupby(["task", "arm"]).agg(n=("p", "size"), sims=("sim_id", "nunique"), reps=("repeat", "nunique"))
    add("C20", "existing DEV out-of-fold predictions recovered (each DEV run predicted once per repeat)", bool((cov.n == cov.sims * cov.reps).all()),
        "; ".join(f"{i[0]} {i[1]}: {r.n} preds, {r.sims} sims x {r.reps} reps" for i, r in cov.iterrows()))
    ck = pd.DataFrame(checks)
    _w(ck, "CHECKS.csv")
    print(ck[["check", "status", "detail"]].to_string(max_colwidth=110))
    return ck


def step_manifest():
    """Run manifest: code revision, environment, and SHA-256 of every committed Week 19 output file."""
    import hashlib
    import platform
    import subprocess
    import importlib.metadata as md
    files = sorted(p for p in OUT.rglob("*") if p.is_file() and "_cache" not in p.parts and p.name not in ("RUN_MANIFEST.json", "full_run_log.txt"))
    rows = [{"path": str(p.relative_to(OUT.parent.parent)).replace("\\", "/"), "bytes": p.stat().st_size,
             "sha256": hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]
    head = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, cwd=OUT.parent.parent).stdout.strip()
    branch = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True, cwd=OUT.parent.parent).stdout.strip()
    man = {"generated_by": "python -m src.week19_temporal_audit all", "code_base_commit": head, "branch": branch,
           "python": platform.python_version(), "packages": {k: md.version(k) for k in ("numpy", "pandas", "scipy", "scikit-learn", "matplotlib", "huggingface_hub")},
           "pins": {"OLD": OLD_REV, "OLD_audit_pin_reused_bytes": "d69dac5bda8b622bc0de316b112815c6056c06ec", "NEW": NEW_REV},
           "outputs": rows}
    (OUT / "provenance" / "RUN_MANIFEST.json").write_text(json.dumps(man, indent=1))
    return man


if __name__ == "__main__":
    step = sys.argv[1] if len(sys.argv) > 1 else "all"
    if step in ("labels", "all"):
        step_labels()
    if step in ("series", "all"):
        step_series()
    if step in ("tables", "all"):
        step_tables()
    if step in ("analysis", "all"):
        step_analysis()
    if step in ("ke", "all"):
        step_ke()
    if step in ("figures", "all"):
        step_figures()
    if step in ("checks", "all"):
        step_checks()
    if step in ("manifest", "all"):
        step_manifest()
